import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { SITE_URL, BRAND } from '@/lib/config';

/**
 * Per-page document head (BRAND-AND-DESIGN §9, UX-STANDARDS §8 "link previews are
 * reassuring and leak-free"). Before this, the app shipped an empty <Head/> — blank
 * browser-tab titles and bare link previews, off-brand for a "trusted private room".
 *
 * Defaults live here and render once from _app; a page overrides them with <Seo title=… />.
 * Every meta carries a stable `key` so next/head dedupes (page wins over the _app default);
 * <title> dedupes automatically (last in tree order wins).
 *
 * PRIVACY: this is brand chrome only. Never pass a target's identity or a specific
 * bounty's brief into a title/description — the public pitch page in particular must stay
 * identity-blind in its link preview (it passes a generic title + noindex).
 */

const SITE = BRAND.name;
const DEFAULT_DESCRIPTION =
  'A private, trusted room for warm professional introductions. Funded proposals meet the people ' +
  'who can actually make them, with the introduced person’s identity kept private until it matters.';

export interface SeoProps {
  /** Page-specific title; composed as "Title · {BRAND.name}". Omit for the site default. */
  title?: string;
  description?: string;
  /** Keep private/transactional surfaces (pitch links, settings) out of search engines. */
  noindex?: boolean;
}

export function Seo({ title, description = DEFAULT_DESCRIPTION, noindex = false }: SeoProps) {
  const fullTitle = title ? `${title} · ${SITE}` : `${SITE} - Skip the cold email.`;

  // Canonical/og:url need an absolute URL, so they only emit when SITE_URL is configured (prod).
  // Path only: strip the query string so canonical points at the clean page, not a tracked variant.
  // A noindex page never advertises a canonical (we don't want it indexed under any URL).
  const { asPath } = useRouter();
  const path = asPath.split(/[?#]/)[0];
  const canonical = SITE_URL && !noindex ? `${SITE_URL}${path === '/' ? '' : path}` : undefined;

  // The 1200x630 link-preview card (public/og.png, generated by scripts/gen-og-image.mjs).
  // Needs an absolute URL. We provide a hardcoded prod fallback so social shares never look bare.
  const ogImage = SITE_URL ? `${SITE_URL}/og.png` : 'https://theintroexchange.com/og.png';

  return (
    <Head>
      {/* Pages Router does NOT auto-inject a viewport tag; without it every page renders
          desktop-zoomed-out on phones (the responsive breakpoints never fire). Lives here
          so it ships on every page via the _app default render. */}
      <meta key="viewport" name="viewport" content="width=device-width, initial-scale=1" />
      <title>{fullTitle}</title>
      <meta key="description" name="description" content={description} />
      {/* Favicons + home-screen icon. An SVG primary (scales crisply, theme-aware) with an
          .ico fallback for legacy chrome; apple-touch-icon is the iOS home-screen tile. The
          theme-color tints mobile browser chrome to the ink brand token (raw hex is required
          here: browser chrome parses it as a literal color, not CSS, so conformance allows it). */}
      <link key="icon-svg" rel="icon" href="/icon.svg" type="image/svg+xml" />
      <link key="icon-ico" rel="icon" href="/favicon.ico" sizes="any" />
      <link key="apple-touch-icon" rel="apple-touch-icon" href="/apple-touch-icon.png" />
      <meta key="theme-color" name="theme-color" content="#0f172a" />
      {canonical && <link key="canonical" rel="canonical" href={canonical} />}
      <meta key="og:site_name" property="og:site_name" content={SITE} />
      <meta key="og:type" property="og:type" content="website" />
      <meta key="og:title" property="og:title" content={fullTitle} />
      <meta key="og:description" property="og:description" content={description} />
      {canonical && <meta key="og:url" property="og:url" content={canonical} />}
      {ogImage && <meta key="og:image" property="og:image" content={ogImage} />}
      {ogImage && <meta key="og:image:width" property="og:image:width" content="1200" />}
      {ogImage && <meta key="og:image:height" property="og:image:height" content="630" />}
      <meta key="twitter:card" name="twitter:card" content={ogImage ? 'summary_large_image' : 'summary'} />
      <meta key="twitter:title" name="twitter:title" content={fullTitle} />
      <meta key="twitter:description" name="twitter:description" content={description} />
      {ogImage && <meta key="twitter:image" name="twitter:image" content={ogImage} />}
      {noindex && <meta key="robots" name="robots" content="noindex, nofollow" />}
    </Head>
  );
}
