import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { SITE_URL, BRAND } from '@/lib/config';

/**
 * Per-page document head (BRAND-AND-DESIGN §9, UX-STANDARDS §8 "link previews are
 * reassuring and leak-free"). Before this, the app shipped an empty <Head/>, blank
 * browser-tab titles and bare link previews, off-brand for a "trusted private room".
 *
 * Defaults live here and render once from _app; a page overrides them with <Seo title=… />.
 * Every meta carries a stable `key` so next/head dedupes (page wins over the _app default);
 * <title> dedupes automatically (last in tree order wins).
 *
 * PRIVACY: this is brand chrome only. Never pass a target's identity or a specific
 * bounty's brief into a title/description, the public pitch page in particular must stay
 * identity-blind in its link preview (it passes a generic title + noindex).
 */

const SITE = BRAND.name;
/*
 * No price here, deliberately. This string and `fullTitle` below are the two surfaces a search
 * engine caches for months, and this component has no catalogue to read: it is rendered on
 * /privacy, /terms and every static page. It said "£49 packs" and "£49 each" while the live
 * shelf ran £29 to £199 (see lib/priceRange.ts for the measurement), so the buyer arrived
 * already told a number that was wrong for 13 of 61 packs. A surface that cannot check a price
 * does not quote one.
 */
const DEFAULT_DESCRIPTION =
  'Mumchimp sells sourced business opportunity packs. Each is an idea passed by the ' +
  'engine: build spec, GTM plan, operations and unit economics, and a QA report with ' +
  'every claim sourced. Instant download.';

export interface SeoProps {
  /** Page-specific title; composed as "Title · {BRAND.name}". Omit for the site default. */
  title?: string;
  description?: string;
  /** Keep private/transactional surfaces (pitch links, settings) out of search engines. */
  noindex?: boolean;
  /**
   * Page-level schema.org structured data, serialised into one ld+json block.
   *
   * Only ever describe what the page actually is. In particular this must never carry
   * `aggregateRating` or `review`: we have no reviews, a fabricated one is an offence under the
   * DMCCA 2024 fake-review provisions, and Google delists structured data that does not match
   * visible page content, so inventing it would be illegal, dishonest and ineffective at once.
   */
  jsonLd?: Record<string, unknown>;
  /**
   * Site-root-relative path of this page's link-preview image, overriding the shared `/og.png`.
   * Pack pages pass their own generated card (`lib/seo/ogImage.ts`) so 49 products stop sharing
   * one picture. Must be a path, not an absolute URL: it is resolved against SITE_URL below, so a
   * preview never points at the wrong environment.
   */
  ogImagePath?: string;
  /** Alt text for the preview image. Screen readers on X/Slack announce it; also a relevance
   *  signal for image search. Defaults to the page title, which is what the card renders. */
  ogImageAlt?: string;
  /** `og:type` for the page. Pack pages are `product`; everything else is a `website`. */
  ogType?: 'website' | 'product' | 'article';
}

export function Seo({
  title,
  description = DEFAULT_DESCRIPTION,
  noindex = false,
  jsonLd,
  ogImagePath,
  ogImageAlt,
  ogType = 'website',
}: SeoProps) {
  const fullTitle = title ? `${title} · ${SITE}` : `${SITE} · sourced business packs.`;

  // Canonical/og:url need an absolute URL, so they only emit when SITE_URL is configured (prod).
  // Path only: strip the query string so canonical points at the clean page, not a tracked variant.
  // A noindex page never advertises a canonical (we don't want it indexed under any URL).
  const { asPath } = useRouter();
  const path = asPath.split(/[?#]/)[0];
  const canonical = SITE_URL && !noindex ? `${SITE_URL}${path === '/' ? '' : path}` : undefined;

  // The 1200x630 link-preview card. `/og.png` (public/, generated by scripts/gen-og-image.mjs) is
  // the site-wide default; a page with its own card passes `ogImagePath` and wins. Needs an
  // absolute URL, so like the canonical it only emits on a configured build.
  const ogImage = SITE_URL ? `${SITE_URL}${ogImagePath ?? '/og.png'}` : undefined;

  return (
    <Head>
      {/* Pages Router does NOT auto-inject a viewport tag; without it every page renders
          desktop-zoomed-out on phones (the responsive breakpoints never fire). Lives here
          so it ships on every page via the _app default render. */}
      <meta key="viewport" name="viewport" content="width=device-width, initial-scale=1" />
      <title>{fullTitle}</title>
      <meta key="description" name="description" content={description} />
      {/* Favicons + home-screen icon. An SVG primary (scales crisply, theme-aware) with an
          .ico fallback for legacy chrome; apple-touch-icon is the iOS home-screen tile. The
          theme-color tints mobile browser chrome to the ink brand token (raw hex is required
          here: browser chrome parses it as a literal color, not CSS, so conformance allows it). */}
      <link key="icon-svg" rel="icon" href="/icon.svg" type="image/svg+xml" />
      <link key="icon-ico" rel="icon" href="/favicon.ico" sizes="any" />
      <link key="apple-touch-icon" rel="apple-touch-icon" href="/apple-touch-icon.png" />
      <meta key="theme-color" name="theme-color" content="#0A0A0A" />
      {canonical && <link key="canonical" rel="canonical" href={canonical} />}
      <meta key="og:site_name" property="og:site_name" content={SITE} />
      <meta key="og:type" property="og:type" content={ogType} />
      <meta key="og:title" property="og:title" content={fullTitle} />
      <meta key="og:description" property="og:description" content={description} />
      {canonical && <meta key="og:url" property="og:url" content={canonical} />}
      {ogImage && <meta key="og:image" property="og:image" content={ogImage} />}
      {ogImage && <meta key="og:image:width" property="og:image:width" content="1200" />}
      {ogImage && <meta key="og:image:height" property="og:image:height" content="630" />}
      {ogImage && <meta key="og:image:alt" property="og:image:alt" content={ogImageAlt ?? fullTitle} />}
      {/* en-GB, stated: prices are GBP and the packs are written in British English. Without it a
          crawler infers locale from the TLD and content, and infers it wrongly often enough that
          US-English variants of these pages get shown to UK searchers. */}
      <meta key="og:locale" property="og:locale" content="en_GB" />
      <meta key="twitter:card" name="twitter:card" content={ogImage ? 'summary_large_image' : 'summary'} />
      <meta key="twitter:title" name="twitter:title" content={fullTitle} />
      <meta key="twitter:description" name="twitter:description" content={description} />
      {ogImage && <meta key="twitter:image" name="twitter:image" content={ogImage} />}
      {ogImage && <meta key="twitter:image:alt" name="twitter:image:alt" content={ogImageAlt ?? fullTitle} />}
      {/* An indexable page opts IN to the largest preview treatments. These are not defaults:
          without `max-image-preview:large` Google shows a thumbnail or nothing at all for the
          pack cards, and `max-snippet:-1` is what allows a full-length snippet to be quoted,
          which is precisely what an AI answer surface needs in order to cite this page usefully.
          A noindex page keeps its existing directive and gets none of this. */}
      {noindex ? (
        <meta key="robots" name="robots" content="noindex, nofollow" />
      ) : (
        <meta
          key="robots"
          name="robots"
          content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
        />
      )}
      {/* A noindex page never emits structured data, there is nothing to be structured for.
          `<` is escaped because the payload carries operator-authored copy (pack titles), and an
          unescaped "</script>" inside a JSON string ends the block and drops the rest of it into
          the document as markup. */}
      {/* The `react/no-danger` rail exists to keep untrusted strings out of an HTML sink, and
          this is the one sink it cannot cover. A <script> element has raw-text content, so a
          React text child would be emitted with `"` as `&quot;` and no crawler could parse the
          block; dangerouslySetInnerHTML is the only way to write it, and is what Next.js
          documents for JSON-LD. What makes it safe is the escaping below, not the rule: the
          payload is JSON.stringify output, so it can never be arbitrary markup. */}
      {jsonLd && !noindex && (
        <script
          key="jsonld"
          type="application/ld+json"
          /* eslint-disable-next-line react/no-danger -- justified above; safe by the escape */
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }}
        />
      )}
    </Head>
  );
}
