#!/usr/bin/env python3
"""Prove the NON-PAYMENT storefront API surface against a running Store.Api.

prove_launch.sh proves the money rail; this proves everything else the storefront serves:
the catalogue listing, single-pack detail, survivorship stats, 404 handling, the auth gates
on the internal/admin endpoints, and CORS. Deterministic HTTP assertions against the real
catalogue (a copy) — no Stripe, no browser. Booted by prove_storefront.sh.

Required env: none beyond API_BASE (default http://localhost:5294). Optional: PROOF_FILE,
ALLOWED_ORIGIN (default http://localhost:3000).
"""
import os
import sys
import time

import requests

API = os.environ.get("API_BASE", "http://localhost:5294")
PROOF_FILE = os.environ.get("PROOF_FILE", "store/launch/storefront-proof.md")
ORIGIN = os.environ.get("ALLOWED_ORIGIN", "http://localhost:3000")

RESULTS: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str) -> bool:
    RESULTS.append((name, ok, detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}", flush=True)
    return ok


def get(path: str, **kw) -> requests.Response:
    return requests.get(f"{API}{path}", timeout=30, **kw)


def main() -> int:
    # --- Catalogue listing -------------------------------------------------
    r = get("/catalog")
    packs = r.json() if r.status_code == 200 else []
    record("catalog.200-list-nonempty", r.status_code == 200 and isinstance(packs, list) and len(packs) > 0,
           f"GET /catalog -> {r.status_code}, {len(packs) if isinstance(packs, list) else '?'} pack(s)")
    fields_ok = all(p.get("id") and p.get("title") and ("price" in p) for p in packs)
    record("catalog.required-fields", bool(packs) and fields_ok,
           "every pack has id + title + price" if fields_ok else "a pack is missing id/title/price")

    # --- Survivorship stats ------------------------------------------------
    rs = get("/catalog/stats")
    stats = rs.json() if rs.status_code == 200 else {}
    listed, registered = stats.get("listed"), stats.get("registered")
    stats_shape = rs.status_code == 200 and isinstance(listed, int) and isinstance(registered, int)
    record("stats.200-shape", stats_shape,
           f"GET /catalog/stats -> {rs.status_code} {{listed:{listed}, registered:{registered}}}")
    record("stats.listed-le-registered", stats_shape and 1 <= listed <= registered,
           f"1 <= listed({listed}) <= registered({registered})")
    record("stats.matches-catalog", stats_shape and listed == len(packs),
           f"stats.listed({listed}) == /catalog count({len(packs)})")

    # --- Single-pack detail + 404 -----------------------------------------
    if packs:
        pid = packs[0]["id"]
        rd = get(f"/catalog/{pid}")
        d = rd.json() if rd.status_code == 200 else {}
        record("detail.200-resolves", rd.status_code == 200 and d.get("id") == pid and len(d) > 3,
               f"GET /catalog/{{id}} -> {rd.status_code}, id matches, {len(d)} fields")
    r404 = get("/catalog/no-such-pack-zzz-000")
    record("detail.unknown-404", r404.status_code == 404,
           f"GET /catalog/<unknown> -> {r404.status_code} (must be 404)")

    # --- Admin / publish auth gates (must reject unauthenticated writes) ---
    ri = requests.post(f"{API}/internal/catalog", json={"id": "x"}, timeout=30)
    record("internal.auth-required", ri.status_code in (401, 403, 503),
           f"POST /internal/catalog (no key) -> {ri.status_code} (must reject, not 2xx)")
    re = requests.post(f"{API}/entitlements", json={"candidateId": "x"}, timeout=30)
    record("entitlements.auth-required", re.status_code in (401, 403, 503),
           f"POST /entitlements (no token) -> {re.status_code} (must reject, not 2xx)")

    # --- CORS for the storefront origin -----------------------------------
    rc = get("/catalog", headers={"Origin": ORIGIN})
    acao = rc.headers.get("Access-Control-Allow-Origin", "")
    record("cors.allow-origin", acao in (ORIGIN, "*"),
           f"Access-Control-Allow-Origin: '{acao}' for Origin {ORIGIN}")

    all_pass = all(ok for _, ok, _ in RESULTS)
    write_proof(all_pass)
    print(f"\n{'STOREFRONT API PROVEN' if all_pass else 'STOREFRONT PROOF FAILED'} "
          f"({sum(1 for _, ok, _ in RESULTS if ok)}/{len(RESULTS)})", flush=True)
    return 0 if all_pass else 1


def write_proof(all_pass: bool) -> None:
    stamp = time.strftime("%Y-%m-%d %H:%M:%S %Z")
    lines = [f"- [{'x' if ok else ' '}] **{name}** — {detail}" for name, ok, detail in RESULTS]
    doc = f"""# Storefront (non-payment) API proof

> Generated by `store_platform/scripts/prove_storefront.sh`. Proves the non-payment API the
> storefront depends on: catalogue listing + required fields, survivorship stats, single-pack
> detail, 404 handling, the auth gates on /internal/catalog + /entitlements, and CORS.

**Date:** {stamp}
**API:** `{API}`
**Verdict:** {f"✅ ALL {len(RESULTS)} CHECKS PASS" if all_pass else "❌ FAILURE — see below"}

## Results
{chr(10).join(lines)}
"""
    os.makedirs(os.path.dirname(PROOF_FILE), exist_ok=True)
    with open(PROOF_FILE, "w") as f:
        f.write(doc)
    print(f"\nProof written to {PROOF_FILE}", flush=True)


if __name__ == "__main__":
    sys.exit(main())
