#!/usr/bin/env python3
"""Prove the BUY BUTTON path for every sellable pack against a running Store.Api.

This is the leg prove_money_path.py deliberately skips: it seeds a fixture pack with a
fake price and synthesizes webhooks, so it never calls Stripe to create a real Checkout
Session. That gap let two real bugs ship unnoticed (stale ProviderPriceId not present in
the connected Stripe account -> "No such price"; AutomaticTax requiring a head-office
address). This driver closes it: for EVERY listed pack in the catalogue it calls the real
`POST /packs/{id}/checkout` endpoint, which calls Stripe, and asserts a real hosted Checkout
Session URL comes back. A stale/invalid price id or a tax/config misconfig fails loudly here.

Assumes Store.Api is already listening against the REAL catalogue db with a real Stripe key
(see prove_checkout.sh). Required env: none beyond API_BASE (default http://localhost:5293).
Optional: PROOF_FILE, BUYER_EMAIL.
"""
import os
import sys
import time

import requests

API = os.environ.get("API_BASE", "http://localhost:5293")
PROOF_FILE = os.environ.get("PROOF_FILE", "store/launch/checkout-proof.md")
BUYER_EMAIL = os.environ.get("BUYER_EMAIL", "launch-test@example.com")

RESULTS: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str) -> bool:
    RESULTS.append((name, ok, detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}", flush=True)
    return ok


def catalog() -> list[dict]:
    r = requests.get(f"{API}/catalog", timeout=30)
    r.raise_for_status()
    d = r.json()
    return d if isinstance(d, list) else d.get("items", d.get("packs", []))


def prove_checkout(pack: dict) -> None:
    pid = pack.get("id", "?")
    title = (pack.get("title") or "")[:42]
    try:
        r = requests.post(
            f"{API}/packs/{pid}/checkout",
            json={"email": BUYER_EMAIL},
            headers={"Origin": "http://localhost:3000"},
            timeout=30,
        )
    except Exception as exc:  # noqa: BLE001
        record(f"checkout:{pid}", False, f"{title} -> request error: {exc}")
        return
    if r.status_code != 200:
        record(f"checkout:{pid}", False, f"{title} -> HTTP {r.status_code}: {r.text[:120].strip()}")
        return
    url = ""
    try:
        url = r.json().get("url", "")
    except Exception:  # noqa: BLE001
        pass
    real = "checkout.stripe.com" in url and ("cs_test_" in url or "cs_live_" in url)
    mode = "LIVE" if "cs_live_" in url else "test" if "cs_test_" in url else "?"
    record(f"checkout:{pid}", real, f"{title} -> {'real ' + mode + ' session' if real else 'no session: ' + url[:80]}")


def write_proof(all_pass: bool, n: int) -> None:
    stamp = time.strftime("%Y-%m-%d %H:%M:%S %Z")
    lines = [f"- [{'x' if ok else ' '}] **{name}** — {detail}" for name, ok, detail in RESULTS]
    doc = f"""# Buy-button (checkout) proof

> Generated by `store_platform/scripts/prove_checkout.sh` against a running Store.Api on the
> REAL catalogue db with a real Stripe key. For every listed pack it calls the real
> `POST /packs/{{id}}/checkout` (which calls Stripe) and asserts a hosted Checkout Session URL
> is returned. This proves every pack's stored ProviderPriceId resolves in the connected
> Stripe account and that checkout config (tax, currency) is accepted.

**Date:** {stamp}
**API:** `{API}`
**Packs proven:** {n}
**Verdict:** {f"✅ ALL {len(RESULTS)} CHECKOUTS REAL" if all_pass else "❌ FAILURE — see below"}

## Per-pack results
{chr(10).join(lines) if lines else "_no listed packs found_"}
"""
    os.makedirs(os.path.dirname(PROOF_FILE), exist_ok=True)
    with open(PROOF_FILE, "w") as f:
        f.write(doc)
    print(f"\nProof written to {PROOF_FILE}", flush=True)


def main() -> int:
    packs = catalog()
    record("catalog.non-empty", len(packs) > 0, f"{len(packs)} listed pack(s) returned by /catalog")
    for pack in packs:
        prove_checkout(pack)
    all_pass = all(ok for _, ok, _ in RESULTS)
    write_proof(all_pass, len(packs))
    print(f"\n{'ALL CHECKOUTS REAL' if all_pass else 'CHECKOUT PROOF FAILED'} "
          f"({sum(1 for _, ok, _ in RESULTS if ok)}/{len(RESULTS)})", flush=True)
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
