#!/usr/bin/env node
/**
* Mumchimp — verification suite.
*
* npm i -D playwright && npx playwright install chromium
* node verify.mjs http://localhost:3000
*
* Exits 0 only when every check passes. There is no partial credit.
* Do not edit this file to make it pass. Fix the site.
*/
import { chromium } from 'playwright';

const BASE = process.argv[2] || 'http://localhost:3000';
const PAGES = ['/', '/pack/a8333b00e91eec66', '/kill-log', '/how-it-works',
'/pricing', '/ideas', '/faq', '/sample'];

const results = [];
const check = (id, ok, detail = '') => results.push({ id, ok: !!ok, detail });

const BANNED = [
'cited sources behind it', 'the price back in month one',
'adversarial pass', 'beachhead', 'non-goals', 'on what stack',
'machine-readable record', 'Was this helpful', 'on the shelf',
'Collections', 'drip feed', 'unit economics', 'productised'
];

const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await ctx.newPage();

// ─────────────────────────── 1 · ONE PACK COUNT ───────────────────────────
const counts = [];
for (const path of PAGES.slice(0, 6)) {
await page.goto(BASE + path, { waitUntil: 'networkidle' });
const body = await page.locator('body').innerText();
const m = body.match(/(\d+)\s+packs/);
if (m) counts.push({ path, n: m[1] });
}
const distinct = [...new Set(counts.map(c => c.n))];
check('C1 one pack count sitewide', distinct.length === 1,
distinct.length === 1 ? `all say ${distinct[0]}` : JSON.stringify(counts));

// ─────────────────────────── per-page checks ───────────────────────────
for (const path of PAGES) {
await page.goto(BASE + path, { waitUntil: 'networkidle' });
const tag = path === '/' ? '/' : path;

// 2 · banned strings
const text = await page.locator('body').innerText();
const hits = BANNED.filter(w => text.includes(w));
check(`C2 no banned copy ${tag}`, hits.length === 0, hits.join(', '));

// 3 · exactly one h1, no heading-level jumps
const heads = await page.$$eval('h1,h2,h3,h4,h5,h6', els => els.map(e => +e.tagName[1]));
const jumps = heads.filter((h, i) => i && h - heads[i - 1] > 1);
check(`C3 heading order ${tag}`,
heads.filter(h => h === 1).length === 1 && jumps.length === 0,
`h1=${heads.filter(h => h === 1).length} jumps=${jumps.length}`);

// 4 · one wordmark in the header
const marks = await page.$$eval('header', hs =>
hs.map(h => (h.innerText.match(/Mumchimp/g) || []).length));
check(`C4 single wordmark ${tag}`, marks.every(n => n <= 1), JSON.stringify(marks));

// 5 · NOTHING overflows its container horizontally
const overflow = await page.$$eval('*', els => els
.filter(e => {
const s = getComputedStyle(e);
if (s.overflowX === 'auto' || s.overflowX === 'scroll') return false;
return e.scrollWidth > e.clientWidth + 2 && e.clientWidth > 0;
})
.slice(0, 8)
.map(e => `${e.tagName}.${(e.className || '').toString().split(' ')[0]}: ${e.scrollWidth}>${e.clientWidth} "${e.innerText.slice(0, 40)}"`));
check(`C5 no horizontal overflow ${tag}`, overflow.length === 0, overflow.join(' | '));

// 6 · nothing sits outside the viewport
const offscreen = await page.$$eval('body *', (els, w) => els
.filter(e => { const r = e.getBoundingClientRect(); return r.width > 0 && (r.right > w + 2 || r.left < -2); })
.slice(0, 6).map(e => `${e.tagName}.${(e.className||'').toString().split(' ')[0]}`), 390);
check(`C6 nothing off-viewport ${tag}`, offscreen.length === 0, offscreen.join(', '));

// 7 · no mid-word truncation rendered into the text
const truncated = (text.match(/\w{2}(…|\.\.\.)/g) || []).slice(0, 5);
check(`C7 no mid-word truncation ${tag}`, truncated.length === 0, truncated.join(', '));

// 8 · no link or button ends in a full stop
const dotted = await page.$$eval('a,button', els => els
.map(e => e.innerText.trim()).filter(t => t.length > 3 && /[a-z]\.$/.test(t)).slice(0, 5));
check(`C8 no trailing full stops ${tag}`, dotted.length === 0, dotted.join(' | '));

// 9 · no nested anchors
const nested = await page.$$eval('a a', els => els.length);
check(`C9 no nested anchors ${tag}`, nested === 0, `${nested} found`);

// 10 · light colour scheme declared
const scheme = await page.$eval('meta[name="color-scheme"]', m => m.content).catch(() => null);
check(`C10 color-scheme light ${tag}`, scheme && scheme.includes('light'), String(scheme));

// 11 · nothing invented: no strikethrough anywhere
const struck = await page.$$eval('*', els => els
.filter(e => getComputedStyle(e).textDecorationLine.includes('line-through')).length);
check(`C11 no strikethrough ${tag}`, struck === 0, `${struck} elements`);

// 12 · the production stylesheet is the one in use
const paper = await page.$eval('body', b => getComputedStyle(b).backgroundColor);
check(`C12 paper background ${tag}`, paper === 'rgb(250, 250, 247)', paper);
}

// ─────────────────────────── landing page specifics ───────────────────────────
await page.goto(BASE + '/?variant=a', { waitUntil: 'networkidle' });

const h1 = (await page.locator('h1').first().innerText()).trim();
check('C13 exact H1', h1 === 'Business ideas with the research already done.', h1);

await page.goto(BASE + '/?variant=b', { waitUntil: 'networkidle' });
const h1b = (await page.locator('h1').first().innerText()).trim();
check('C13b challenger H1', h1b === "Skip 6 months of research. Launch a business that's already vetted.", h1b);

const dots = await page.$$eval('.ratio i', els => ({
total: els.length,
alive: els.filter(e => e.classList.contains('alive')).length
})).catch(() => ({ total: 0, alive: 0 }));
check('C14 hero ratio device', dots.total === 100 && dots.alive === 6, JSON.stringify(dots));

// rows live inside ONE bordered container, not as separate floating cards
const rowModel = await page.$$eval('.rows', cs => cs.map(c => ({
rows: c.querySelectorAll(':scope > .row').length,
gap: getComputedStyle(c).rowGap
}))).catch(() => []);
check('C15 single row container', rowModel.length > 0 && rowModel[0].rows >= 3,
JSON.stringify(rowModel[0] || {}));

// proof lines use exactly one format
const proofs = await page.$$eval('.proof', els => els.map(e => e.innerText.trim()));
const badProof = proofs.filter(p => !/^\d+ sources$|^\d+× payback · \d+ sources$/.test(p));
check('C16 one proof-line format', badProof.length === 0, badProof.slice(0, 4).join(' | '));

// ─────────────────────────── kill log specifics ───────────────────────────
await page.goto(BASE + '/kill-log', { waitUntil: 'networkidle' });
const dchips = await page.$$eval('.filterstrip .dchip', els => els.length).catch(() => 0);
check('C17 dark filter strip', dchips >= 4, `${dchips} dark chips`);

const reasoningVisible = await page.$$eval('.klrow p', els =>
els.filter(e => e.innerText.trim().length > 40).length).catch(() => 0);
check('C18 kill reasoning visible', reasoningVisible >= 3, `${reasoningVisible} rows with reasoning`);

// ─────────────────────────── desktop pass ───────────────────────────
await page.setViewportSize({ width: 1280, height: 900 });
await page.goto(BASE + '/', { waitUntil: 'networkidle' });
const menuHidden = await page.$eval('.icon-btn.menu', e => getComputedStyle(e).display)
.catch(() => 'missing');
check('C19 menu button hidden on desktop', menuHidden === 'none', menuHidden);

const navVisible = await page.$$eval('.nav-d a', els => els.length).catch(() => 0);
check('C20 desktop nav present', navVisible >= 4, `${navVisible} links`);

await browser.close();

// ─────────────────────────── report ───────────────────────────
const fails = results.filter(r => !r.ok);
for (const r of results) {
console.log(`${r.ok ? 'PASS' : 'FAIL'} ${r.id}${r.detail ? ' — ' + r.detail : ''}`);
}
console.log(`\n${results.length - fails.length}/${results.length} passed`);
if (fails.length) {
console.log('\nFAILURES:');
for (const f of fails) console.log(`  ${f.id} — ${f.detail}`);
process.exit(1);
}
console.log('ALL CHECKS PASSED');
