#!/usr/bin/env python3
"""Write a session handoff that another session cannot overwrite.

    python scripts/handoff.py --write handoff.md     # file in, session-stamped file out
    python scripts/handoff.py --index                # rebuild LATEST.md as an index
    python scripts/handoff.py --read                 # print every live session's handoff

WHY THIS EXISTS
---------------
`checkpoints/LATEST.md` is one file, and on 2026-08-17 there were 18 Claude processes and
58 worktrees against this checkout, all writing to it. A handoff written at 09:45 was gone
by 09:55, replaced by a different session's merge notes. The work was not lost — it was in
git — but the record of what a session had just decided was, which is exactly what a
handoff is for.

There is already a memory recording this failure. It was recorded and not fixed, because
the fix is mechanical and nobody made it mechanical.

The fix: every session writes `checkpoints/session-<id>.md`, keyed on the session id, so
two sessions cannot collide. `LATEST.md` becomes a generated INDEX of them, newest first,
which is what a fresh session actually needs — not one session's notes, but everyone's.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

CHECKPOINTS = Path(
    "~/.claude/projects/-Users-chidionyema-Documents-code-prospector/checkpoints"
).expanduser()
INDEX = CHECKPOINTS / "LATEST.md"
SESSION_RE = re.compile(r"^session-(?P<id>[A-Za-z0-9_-]+)\.md$")


def session_id() -> str:
    """A stable id for THIS session.

    The scratchpad path carries the session uuid, which is the only identifier available to
    a script the agent shells out to. The fallback is the CHECKOUT, never a pid: a pid
    changes on every shell the agent opens, so the same session would publish a new handoff
    file each time and the index would fill with near-duplicates. "One session, one worktree"
    is the working rule here, which makes the worktree the honest identity."""
    for var in ("CLAUDE_SESSION_ID", "CLAUDE_SCRATCHPAD", "TMPDIR"):
        val = os.environ.get(var, "")
        m = re.search(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", val)
        if m:
            return m.group(0)[:8]
    return Path.cwd().name[:16] or "unknown"


def _branch() -> str:
    try:
        p = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                           capture_output=True, text=True, timeout=15)
        return p.stdout.strip() or "?"
    except (OSError, subprocess.SubprocessError):
        return "?"


def write(body_path: Path, sid: str) -> Path:
    CHECKPOINTS.mkdir(parents=True, exist_ok=True)
    body = body_path.read_text(encoding="utf-8")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = CHECKPOINTS / f"session-{sid}.md"
    header = (f"<!-- session {sid} | {stamp} | branch {_branch()} | cwd {Path.cwd()} -->\n"
              f"# Session {sid} — {stamp}\n\n")
    out.write_text(header + body, encoding="utf-8")
    return out


def handoffs() -> list[tuple[float, Path, str]]:
    """Every session handoff, newest first, with its first real heading."""
    rows = []
    for p in CHECKPOINTS.glob("session-*.md"):
        if not SESSION_RE.match(p.name):
            continue
        title = ""
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("## ") or (line.startswith("# ") and "Session " not in line):
                title = line.lstrip("# ").strip()
                break
        rows.append((p.stat().st_mtime, p, title))
    return sorted(rows, reverse=True)


def build_index() -> Path:
    rows = handoffs()
    lines = [
        "# Session handoffs — newest first",
        "",
        "Generated by `scripts/handoff.py --index`. **Do not hand-edit**: it is rebuilt.",
        "",
        "One shared `LATEST.md` was overwritten between sessions, so each session now",
        "writes its own `session-<id>.md` and this file indexes them. Read the top two or",
        "three before starting work — that is how you find out what the other sessions are",
        "holding, which nothing was doing before 2026-08-17.",
        "",
    ]
    if not rows:
        lines.append("_No session handoffs yet._")
    for mtime, path, title in rows:
        when = datetime.fromtimestamp(mtime, timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines.append(f"- **{when}** — [{path.name}]({path.name}) — {title or '(no title)'}")
    INDEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return INDEX


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", metavar="FILE", help="markdown body to publish as this session's handoff")
    ap.add_argument("--index", action="store_true", help="rebuild LATEST.md as an index")
    ap.add_argument("--read", action="store_true", help="list every session handoff")
    ap.add_argument("--session", default="", help="override the session id")
    args = ap.parse_args()

    sid = args.session or session_id()

    if args.write:
        src = Path(args.write)
        if not src.exists():
            print(f"no such file: {src}", file=sys.stderr)
            return 2
        out = write(src, sid)
        idx = build_index()
        print(f"wrote {out}")
        print(f"index {idx} ({len(handoffs())} session handoff(s))")
        return 0

    if args.index:
        idx = build_index()
        print(f"rebuilt {idx} ({len(handoffs())} session handoff(s))")
        return 0

    if args.read or True:
        for mtime, path, title in handoffs():
            when = datetime.fromtimestamp(mtime, timezone.utc).strftime("%Y-%m-%d %H:%M")
            print(f"{when}  {path.name:<28} {title[:70]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
