"""Build the storefront's free-sample fixture FROM a real pack, through the real renderers.

WHY THIS TOOL EXISTS
--------------------
`/sample` is the page that tells a visitor what they get for their money, and until 2026-08-15
it was backed by a hand-maintained JSON blob (`Store.Web/src/data/sample-report.json`) whose
own dossier is no longer on disk::

    $ ls store/dossiers/0f2109fb198341a4.pass.json
    ls: no such file

So the page promising "exactly as a buyer receives it" was showing something no buyer could
receive and nothing could re-derive. That is the drift this tool removes: the fixture is now
GENERATED by the same modules that build the bundle, so a change to the pack changes the
sample, and a sample that has gone stale is a failing regeneration rather than a silent lie.

WHAT IT EMITS
-------------
The first three sections of the reading order, in full, as structured blocks -- plus the NAMES
of the eleven it does not show. The founder chose that boundary on 2026-08-15 over giving away
a whole pack: an excerpt that stops in a visible place is honest, where "a whole report, free,
nothing held back" sitting above a footer that admits a pack "adds the build spec, the go to
market plan, and the operations playbook" was not (`sample.tsx:174` against `:389`).

BLOCKS AND NODES, NOT MARKDOWN AND NOT HTML
-------------------------------------------
The storefront renders no markdown (it would print `**bold**` literally), and handing it a blob
of HTML would put the pack's styling in charge of a page that has its own -- and would make the
one page arguing "we do not overclaim" the page with five `react/no-danger` suppressions on it.

So this emits two levels of typed data and no markup at all. A section is a list of BLOCKS --
`p`, `h2`, `h3`, `hr`, `ul`, `callout`, `source` -- and a block's inline formatting is a list of
NODES: bare strings, and `{"tag": "strong"|"em"|"a"|"code", "children": [...]}`. The page builds
React elements from those. `_InlineTree` RAISES on any tag outside that set rather than stripping
it, because the one thing this file must never do is widen what the storefront renders.

Run it from the worktree, pointing at wherever the dossiers live::

    python tools/build_sample_fixture.py <pack_id> \
        --dossier-dir /Users/…/prospector/store/dossiers \
        --out /Users/…/Store.Web/src/data/sample-report.json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import mistune  # noqa: E402
from make_sample_report import report_fields  # noqa: E402

from prospector import bridge, pack_field, pack_floors, pack_manifest, pack_offer  # noqa: E402
from prospector.config import store_root  # noqa: E402
from prospector.plain_text import publish_pass_document  # noqa: E402

#: The three sections the sample shows, in reading order. Named by FILENAME so this list and
#: `bridge.BUNDLE_READING_ORDER` cannot silently disagree about what section three is -- the
#: check below fails the build if they do.
SHOWN = ("00_Executive_Summary.md", "The_Offer.md", "The_Field.md")

#: What each withheld section is, in the buyer's terms. These describe the SECTION, never the
#: idea, so they are claim-free and stay true across every pack: "what would sink this" is a
#: fact about the document's structure, not an assertion about the market.
WITHHELD_BLURB = {
    "04_Financial_Model.md":
        "What it costs to run, what it has to charge, and the figure it breaks even at — with "
        "the assumptions listed separately so you can change ours for yours.",
    "What_Would_Sink_This.md":
        "The case against, at full strength: every check the evidence went against, every "
        "question the desk could not settle, and the searches we ran before giving up on it.",
    "01_Blueprint_BuildSpec.md":
        "The smallest thing worth charging for, specified — what it does, what it does not do, "
        "and what you can leave until it sells.",
    "02_Marketing_Plan_GTM.md":
        "Where the first ten customers come from, in order of how cheaply you can test each "
        "one.",
    "03_Operations_Plan.md":
        "What a week looks like once it works: the recurring jobs, the ones to automate first, "
        "and the point at which it stops fitting around a day job.",
    "05_First_Week_Checklist.md":
        "Fourteen days of specific work, sequenced so the cheapest thing that could kill the "
        "idea happens first.",
    "The_Toolkit.md":
        "The questions to ask, drawn from the checks this pack could not close — plus a first "
        "outreach message and a one-page decision memo with a kill line on it.",
    "Marketing_Assets.md":
        "Copy you can paste: the listing, the pitch, the outreach — written only from claims "
        "that survived checking.",
    "How_To_Know_In_30_Days.md":
        "One test. The single thing that can come back false soonest, with what counts as a no "
        "decided before you start.",
    "Evidence_and_Constraints.md":
        "Every source behind every claim, in one place, each one a link you can open.",
    "QA_Report.md":
        "The full record of every check: the queries we ran, the passages we read, the verdict, "
        "and the confidence we put on it.",
}

_INLINE = mistune.create_markdown(escape=True, plugins=[])
_ALLOWED_TAGS = {"strong", "em", "a", "code"}
# `**host**, 2024 — label` / `[url](url)` / `> quote`, the three lines `pack_field._passage_block`
# emits per source. Coalesced into ONE `source` block so the storefront can render a cited card
# instead of three unrelated paragraphs with a stray link between them.
_ATTRIB = re.compile(r"^\*\*(?P<host>[^*]+)\*\*(?:,\s*(?P<year>\d{4}))?"
                     r"(?:\s*—\s*(?P<label>.+?))?\s*$")
_LINK_ONLY = re.compile(r"^\[(?P<url>https?://[^\]]+)\]\((?P=url)\)$")

# URLs whose attribution line survived but whose excerpt did not -- see the drop in `_blocks`.
# Module-level because `_blocks` is called once per shown section and `main` reports the total.
_DROPPED_SOURCES: List[str] = []
# Anything else this tool removed on the way through, printed by `main`. A build that trims
# quietly reads as "we published everything we had" to the next person who runs it.
_NOTES: List[str] = []


def _block_text(block: Any) -> str:
    """Every string inside one typed block, in order, joined with single spaces.

    Blocks nest two ways -- `nodes` for block-level children, `children` for inline ones -- so
    this walks whatever it is given rather than knowing the schema. Used to compare a rendered
    block against a plain dossier field.
    """
    out: List[str] = []

    def walk(node: Any) -> None:
        if isinstance(node, str):
            out.append(node)
        elif isinstance(node, list):
            for item in node:
                walk(item)
        elif isinstance(node, dict):
            for key in ("nodes", "children", "text", "items"):
                if key in node:
                    walk(node[key])

    walk(block)
    return " ".join(" ".join(out).split())


class _InlineTree(HTMLParser):
    """mistune's inline HTML to a nested node tree, refusing anything off the whitelist.

    NO HTML CROSSES THIS BOUNDARY, AND THAT IS THE POINT
    ---------------------------------------------------
    The first version of this tool emitted `{"html": "<strong>pain reality:</strong> …"}` and the
    page set it with `dangerouslySetInnerHTML`. It was safe — the whitelist below was already
    enforced — but ESLint was right to refuse it::

        $ npx eslint src/pages/sample.tsx
        84:11  error  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger
        ✖ 5 problems

    Five suppressions on the one page whose entire argument is "we do not overclaim, check us"
    is the wrong trade. Emitting a tree instead means the storefront builds React elements from
    typed data and there is no HTML string anywhere in the path, so the rule stays on for the
    whole codebase and this page needs no exception.

    A tag outside the whitelist RAISES rather than being stripped. Stripping would let a renderer
    change silently lose content; raising makes it a failed regeneration, which is the failure
    mode this whole tool exists to convert drift into.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root: List[Any] = []
        self._stack: List[List[Any]] = [self.root]
        self._open: List[str] = []

    def handle_starttag(self, tag: str, attrs) -> None:
        if tag.lower() not in _ALLOWED_TAGS:
            raise ValueError(
                f"a block would put <{tag}> into the storefront; only {sorted(_ALLOWED_TAGS)} "
                "are allowed. Fix the renderer, not this whitelist.")
        node: Dict[str, Any] = {"tag": tag.lower(), "children": []}
        if node["tag"] == "a":
            href = dict(attrs).get("href") or ""
            if not href.startswith(("http://", "https://")):
                raise ValueError(f"link target {href!r} is not an absolute http(s) URL")
            node["href"] = href
        self._stack[-1].append(node)
        self._stack.append(node["children"])
        self._open.append(node["tag"])

    def handle_endtag(self, tag: str) -> None:
        # Matched explicitly rather than popping on sight: an unbalanced close would otherwise
        # unwind the stack and silently reparent the rest of the paragraph under the wrong node.
        if self._open and self._open[-1] == tag.lower():
            self._open.pop()
            self._stack.pop()

    def handle_data(self, data: str) -> None:
        if data:
            self._stack[-1].append(data)


def _inline(text: str) -> List[Any]:
    """Markdown inline formatting as a nested node tree: strings, and `{tag, children}` dicts."""
    out = _INLINE(text).strip()
    if out.startswith("<p>") and out.endswith("</p>"):
        out = out[3:-4]
    parser = _InlineTree()
    parser.feed(out)
    parser.close()
    return parser.root


def _blocks(markdown: str) -> List[Dict[str, Any]]:
    """A section's markdown as typed blocks, with its `# H1` dropped (the page owns the title)."""
    lines = markdown.splitlines()
    out: List[Dict[str, Any]] = []
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.strip()
        i += 1
        if not line:
            continue
        if line.startswith("# "):
            continue                                   # the section title, rendered by the page
        if line.startswith("## "):
            out.append({"type": "h2", "nodes": _inline(line[3:])})
            continue
        if line.startswith("### "):
            out.append({"type": "h3", "nodes": _inline(line[4:])})
            continue
        if set(line) == {"-"} and len(line) >= 3:
            out.append({"type": "hr"})
            continue
        if line.startswith("> "):
            out.append({"type": "p", "nodes": _inline(line[2:]), "quote": True})
            continue
        if line.startswith("- ") or line.startswith("* "):
            items = []
            i -= 1
            while i < len(lines) and lines[i].strip()[:2] in ("- ", "* "):
                items.append(_inline(lines[i].strip()[2:]))
                i += 1
            out.append({"type": "ul", "items": items})
            continue

        attrib = _ATTRIB.match(line)
        nxt = lines[i].strip() if i < len(lines) else ""
        link = _LINK_ONLY.match(nxt) if attrib else None
        if attrib and link:
            i += 1
            quote = ""
            while i < len(lines) and not lines[i].strip():
                i += 1
            if i < len(lines) and lines[i].strip().startswith("> "):
                quote = lines[i].strip()[2:]
                i += 1
            # A SOURCE WITH NO QUOTE IS NOT A CARD (2026-08-15).
            #
            # `pack_field._passage_block` (`prospector/pack_field.py:263`) deliberately withholds
            # an excerpt it has already printed in this section: two URLs on one site routinely
            # return byte-identical body text, and the same paragraph under two links makes the
            # evidence look padded rather than corroborated. In markdown the result is fine — an
            # attribution line and a link, which reads as a second reference.
            #
            # Rendered as a CARD it is not fine. The section says "Excerpts from the pages the
            # search returned ... Quoted rather than summarised", and a card whose entire purpose
            # is the quote arrives empty underneath that sentence. Measured on the shipped sample
            # fixture: `host='getyooz.com' quote_len=0`, the first card the reader meets.
            #
            # So the quoteless source is dropped from the excerpt rather than rendered hollow, and
            # the drop is REPORTED by `main` below. A cap that trims silently reads as "we showed
            # you everything" when it did not; this one has to say so out loud. The source itself
            # is not lost — the pack's own sources section lists every URL, and `sourceCount` on
            # this fixture still counts it.
            if not quote:
                _DROPPED_SOURCES.append(link.group("url"))
                continue
            out.append({
                "type": "source",
                "host": attrib.group("host"),
                "year": attrib.group("year") or "",
                "label": attrib.group("label") or "",
                "url": link.group("url"),
                "quote": quote,
            })
            continue

        # A lone bolded line is a callout in every one of these renderers -- the payer, the
        # one-liner. It is given its own type so the page can set it apart typographically
        # rather than printing a paragraph that happens to be entirely bold.
        if line.startswith("**") and line.endswith("**") and line.count("**") == 2:
            out.append({"type": "callout", "nodes": _inline(line[2:-2])})
            continue
        out.append({"type": "p", "nodes": _inline(line)})
    return out


def build(pack_id: str, dossier_dir: Path) -> Dict[str, Any]:
    path = dossier_dir / f"{pack_id}.pass.json"
    data = json.loads(path.read_text())
    dossier = pack_manifest.dossier_from_dict(data)
    cand = dossier.candidate
    checks = list(getattr(dossier, "checks", None) or [])

    order = list(bridge.BUNDLE_READING_ORDER)
    if tuple(order[:3]) != SHOWN:
        raise SystemExit(
            f"the reading order starts {order[:3]}, but the sample shows {list(SHOWN)}. "
            "The free excerpt has drifted from the pack's own first three sections; decide "
            "which is right and change BOTH.")

    rendered = {
        "00_Executive_Summary.md": pack_floors.exec_summary_md(cand, checks),
        "The_Offer.md": pack_offer.render(dossier),
        "The_Field.md": pack_field.render(dossier),
    }
    excerpt = []
    for name in SHOWN:
        md = publish_pass_document(rendered[name] or "")
        if not md.strip():
            raise SystemExit(f"{name} rendered empty for {pack_id}; pick a richer pack.")
        excerpt.append({
            "id": name.replace(".md", "").lstrip("0123456789_").lower().replace("_", "-"),
            "title": bridge._SECTION_TITLES[name],
            "blocks": _blocks(md),
        })

    # THE PAGE ALREADY SAID THAT (2026-08-15, founder on the live sample page).
    #
    # `sample.tsx` prints the one-liner as the standfirst, directly under the pack's title,
    # because that is where a newspaper puts it -- and `exec_summary_md` opens its own section
    # with the same sentence for exactly the same reason. Both are right in isolation. Rendered
    # together they put one sentence twice on a reader's screen with a section number between
    # them, which is the first thing anybody sees on the free sample.
    #
    # Dropped HERE rather than in the renderer: the pack is a standalone document and its
    # opening section must still carry its own standfirst. It is this page that says it twice.
    # Compared as normalised text, so a bolded copy still matches the plain field.
    one_liner = " ".join(str(getattr(cand, "one_liner", "") or "").split()).strip().rstrip(".")
    first_blocks = excerpt[0]["blocks"] if excerpt else []
    if one_liner and first_blocks:
        head = _block_text(first_blocks[0]).strip().rstrip(".")
        if head.casefold() == one_liner.casefold():
            first_blocks.pop(0)
            _NOTES.append("dropped the repeated one-liner from the first excerpt section "
                          "(the page prints it as the standfirst)")

    withheld = []
    for name in order[3:]:
        blurb = WITHHELD_BLURB.get(name)
        if blurb is None:
            raise SystemExit(f"no blurb for withheld section {name}; add one to WITHHELD_BLURB "
                             "rather than letting the sample list a section it cannot describe.")
        withheld.append({"title": bridge._SECTION_TITLES[name], "blurb": blurb})

    # A SUPERSET, not a replacement. `report_fields` owns every key the four evidence components
    # and their test already read (`id`, `title`, `oneLiner`, `whoPays`, `whyNow`, `verifiedAt`,
    # `supported`, `total`, `sourceCount`, `scores`, `premortem`, `adversarial`, `checks`); this
    # tool only ADDS the excerpt and the boundary. Nothing here re-derives one of those fields
    # under a second name — two counts of the same thing on one page eventually disagree, and the
    # page whose whole argument is "check our numbers" is the worst place for that.
    return {
        **report_fields(pack_id, data),
        "sectionsTotal": len(order),
        "sectionsShown": len(SHOWN),
        "excerpt": excerpt,
        "withheld": withheld,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("pack_id")
    ap.add_argument("--dossier-dir", type=Path, default=store_root() / "dossiers")
    ap.add_argument("--out", type=Path)
    args = ap.parse_args()

    fixture = build(args.pack_id, args.dossier_dir)
    text = json.dumps(fixture, indent=2, ensure_ascii=False) + "\n"
    if args.out:
        args.out.write_text(text, encoding="utf-8")
        counts = {b["type"] for s in fixture["excerpt"] for b in s["blocks"]}
        print(f"wrote {args.out} ({len(text):,} bytes)  {fixture['title']!r}")
        for s in fixture["excerpt"]:
            print(f"  {s['title']:<38} {len(s['blocks']):>3} blocks")
        print(f"  withheld: {len(fixture['withheld'])} sections")
        for url in _DROPPED_SOURCES:
            print(f"  dropped (no excerpt to quote): {url}")
        for note in _NOTES:
            print(f"  {note}")
        print(f"  block types: {sorted(counts)}")
        print(f"  legacy fields: {fixture['supported']}/{fixture['total']} supported, "
              f"{fixture['sourceCount']} sources, {len(fixture['checks'])} checks, "
              f"{len(fixture['premortem']['sources'])} premortem chips")
    else:
        print(text)


if __name__ == "__main__":
    main()
