/**
 * MOCKUP OUTLINE
 *
 * Turns all twelve drawings into one readable spec, `docs/design/MOCKUP_MARKUP.md`.
 *
 * Why: the storefront was being edited against fragments of one page, and the other eleven had
 * never been opened. Raw markup for twelve pages is 4,860 lines, most of it a shared <style> head
 * repeated per file. This strips that and prints what actually matters: every element inside
 * <main>, indented, with its class and its text, so the whole specification is readable in one
 * sitting and a section cannot be missed because nobody scrolled to it.
 *
 * Run: node scripts/mockup_outline.mjs
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(process.cwd(), '../../..');
const DIR = path.join(ROOT, 'docs/design/mumchimp-build-bundle/mockups');
const REPORT = path.join(ROOT, 'docs/design/MOCKUP_MARKUP.md');

/* Elements that carry no structure worth printing. Their text still shows up on the parent line. */
const SKIP = new Set(['svg', 'path', 'circle', 'rect', 'line', 'polyline', 'g', 'br', 'script', 'style']);

/** A tiny tag walker. The drawings are hand-written, well-formed HTML, so a real parser is
 *  overkill; this only needs to be right about nesting depth, class, and text. */
function outline(html) {
  const main = /<main[^>]*>([\s\S]*)<\/main>/.exec(html);
  const body = main ? main[1] : html;
  const out = [];
  let depth = 0;
  const re = /<!--([\s\S]*?)-->|<(\/?)([a-zA-Z][\w-]*)((?:"[^"]*"|'[^']*'|[^>"'])*?)(\/?)>|([^<]+)/g;
  let pendingText = '';
  const flush = () => {
    const t = pendingText.replace(/\s+/g, ' ').trim();
    pendingText = '';
    if (t && out.length) out[out.length - 1] += `  "${t.length > 90 ? `${t.slice(0, 89)}…` : t}"`;
  };
  let m;
  while ((m = re.exec(body)) !== null) {
    const [, comment, close, tag, attrs, selfClose, text] = m;
    if (comment !== undefined) {
      flush();
      out.push(`${'  '.repeat(Math.max(0, depth))}<!-- ${comment.replace(/\s+/g, ' ').trim()} -->`);
      continue;
    }
    if (text !== undefined) { pendingText += text; continue; }
    if (SKIP.has(tag.toLowerCase())) continue;
    if (close) { flush(); depth = Math.max(0, depth - 1); continue; }
    flush();
    const cls = /class="([^"]*)"/.exec(attrs || '');
    const style = /style="([^"]*)"/.exec(attrs || '');
    let label = tag;
    if (cls) label += `.${cls[1].trim().split(/\s+/).join('.')}`;
    if (style) label += ` {${style[1].replace(/\s+/g, ' ').trim()}}`;
    out.push(`${'  '.repeat(depth)}${label}`);
    if (!selfClose) depth += 1;
  }
  flush();
  return out.join('\n');
}

const files = (await readdir(DIR)).filter((f) => f.endsWith('.html')).sort();
const parts = [
  '# The drawings, as one readable spec',
  '',
  'Generated by `store_platform/src/Store.Web/scripts/mockup_outline.mjs` from',
  '`docs/design/mumchimp-build-bundle/mockups/`. Everything inside `<main>`, indented by nesting,',
  'with each element\'s class, any inline style, and its text. Do not edit by hand.',
  '',
  'This exists because the site was being built against fragments of one page. The whole',
  'specification is here, all twelve pages, so nothing gets missed for want of scrolling.',
  '',
];
for (const f of files) {
  const html = await readFile(path.join(DIR, f), 'utf8');
  parts.push(`## ${f}`, '', '```', outline(html), '```', '');
}
await writeFile(REPORT, parts.join('\n'));
console.log(`wrote ${REPORT} from ${files.length} drawings`);
