"""A pack registered with no sector must say so in the run log.

Not guessing a sector is correct and stays correct — the vocabulary is closed, the storefront
routes buyers on it, and an invented category is an unsourced claim. But silence is a separate
failure: four of the twenty-six packs live on 2026-07-31 (CureSafe Strip, SpatWindow,
StrikeShield, SailCert) carried no facets at all, and nothing had ever announced it, so they sat
on the shelf reachable only by search until someone read the catalogue by hand.

The publish must not fail on this — an untagged pack is still a real, sellable pack — so what is
asserted here is that it is LOUD and that it still lists.
"""
from __future__ import annotations

import logging

import pytest

# The financial model is never free prose in production: _validate_artifact_shape forces a
# dict and artifacts.py:258 renders it through _render_financial_model, so every real pack
# carries these sections and Python-computed (arithmetically exact) figures. The publish
# gate lints it (pack_linter), so the fixture below has to be the shape the pipeline
# actually emits. Deliberately duplicated rather than imported across test modules —
# tests/unit is not a package, so a cross-file import breaks collection.
from prospector.artifacts import _render_financial_model
from prospector.bridge import EngineBridge
from prospector.models import Candidate, CheckResult, Decision, Dossier, Verdict

# Generated by the renderer under test, never transcribed. Three copies of this fixture
# had been hand-typed across the suite, so a heading change went red in 22 tests while the
# thing they were guarding — that publish, lint and the renderer agree — was never checked.
_FIN_INPUTS = {
    "revenue_model": "subscription",
    "monthly_price": 50, "target_customers_month_1": 10,
    "target_customers_month_12": 120, "estimated_cac_gbp": 100,
    "estimated_monthly_churn_pct": 5.0, "cost_of_goods_pct": 12,
    "overhead_month_1_gbp": 200,
}
RENDERED_FINANCIAL_MODEL = _render_financial_model(_FIN_INPUTS, [], "£")


class _FakeProvisioner:
    def create_product(self, name, description, metadata):
        return "prod_real_123"

    def create_price(self, product_id, amount_pence, currency="gbp"):
        return "price_real_123"


@pytest.fixture
def bridge(monkeypatch, tmp_path):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("STORE_INTERNAL_API_KEY", "test-internal-key")

    class _Thresholds:
        confidence_floor = 0.0

    class _Cfg:
        entitlements_api_key = "test-entitlements-key"
        store_payments = {"active_provider": "stripe"}
        thresholds = _Thresholds()
        listing = {"price_pence": 4900}

    b = EngineBridge(_Cfg())
    b.entitlements_check = lambda candidate_id: True
    b.stripe = _FakeProvisioner()
    b.r2.upload = lambda path, key: True

    calls: list[dict] = []
    b._update_catalog = lambda **kwargs: (calls.append(kwargs), True)[1]
    b.catalog_calls = calls
    return b


def _dossier(facets, automatability=None, structural_form=""):
    """A publishable PASS whose listing carries `facets` (or omits the block entirely).

    `automatability` / `structural_form` are the two candidate fields the publish path derives
    from; they default to absent so every pre-existing test here keeps exercising the
    nothing-to-derive path.
    """
    body = "## Section\n\nGrounded prose about the opportunity. " * 20
    listing = {
        "type": "listing_page",
        "copy": "# SpatWindow\n\nA per-lease closure forecast for owner-operated UK oyster and "
                "mussel farms: storm-overflow telemetry, rainfall and tide fused into a harvest "
                "window, so stock is moved before a downgrade lands rather than after.",
    }
    if facets is not None:
        listing["facets"] = facets
    cand = Candidate(
        candidate_id="c" * 16,
        title="SpatWindow",
        one_liner="Per-lease closure forecast for UK shellfish farms.",
        market="uk",
        who_pays="owner-operated shellfish farms",
        why_now="new sampling rules",
    )
    cand.automatability = automatability
    cand.structural_form = structural_form
    artifacts = {k: f"# {k}\n\n{body}" for k in
                 ("build_spec", "gtm_plan", "ops_plan", "financial_model")}
    # The financial model is never free prose in production (artifacts.py:258 renders it
    # through _render_financial_model), and the publish gate now lints it — so the fixture
    # carries the rendered shape with arithmetically exact figures.
    artifacts["financial_model"] = RENDERED_FINANCIAL_MODEL
    cand.tags = {
        "artifacts": artifacts,
        "marketing": [listing],
    }
    return Dossier(
        candidate=cand,
        decision=Decision.PASS,
        # A PASS needs the LANE'S decisive check grounded, not merely one supported check: dossier.py:167 mints Decision.PASS only when `moat_grounded >= 1` and KILLs `moat_ungrounded` otherwise. This candidate carries ambition_tier="" — the default lane, moat_critical_checks=[value_durability, incumbency] — so a lone non-decisive check described a dossier the engine cannot produce.
        checks=[CheckResult(check_name="buyer_intent", verdict=Verdict.SUPPORTED, confidence=0.8,
                            rationale="Growers search for closure guidance.",
                            citations=[], sources=[], queries=[]),
                CheckResult(check_name="value_durability", verdict=Verdict.SUPPORTED,
                            confidence=0.8, rationale="Closure rules re-issue each season.",
                            citations=[], sources=[], queries=[])],
        created_at="2026-07-31T00:00:00Z",
    )


def _warnings(caplog):
    return [r.getMessage() for r in caplog.records if r.levelno >= logging.WARNING]


class TestSectorlessPublishIsAnnounced:
    def test_a_missing_facets_block_warns(self, bridge, caplog):
        with caplog.at_level(logging.WARNING, logger="prospector.bridge"):
            bridge.publish_pass(_dossier(None))
        warned = [m for m in _warnings(caplog) if "NO sector" in m]
        assert warned, f"no sector-less warning; warnings were {_warnings(caplog)}"
        # The message has to be actionable on its own: which pack, and where to fix it.
        assert "c" * 16 in warned[0]
        assert "facets-backfill.json" in warned[0]

    def test_the_warning_names_every_absent_facet(self, bridge, caplog):
        """A pack with only `effort` is still mostly untagged — the log must say so."""
        with caplog.at_level(logging.WARNING, logger="prospector.bridge"):
            bridge.publish_pass(_dossier({"effort": "automatable"}))
        warned = [m for m in _warnings(caplog) if "NO sector" in m]
        assert warned
        # Matched on the rendered list, not on substrings of the whole message: the message
        # also echoes the facets block it was given, so a bare `"effort" not in message`
        # would pass or fail for the wrong reason.
        assert (
            "Absent facets: ['advantages', 'commitment', 'mechanism', 'payer', 'sector']"
            in warned[0]
        ), warned[0]

    def test_a_sector_less_pack_is_still_listed(self, bridge, caplog):
        # Deliberate: not tagging is not a reason to withhold a real pack from sale. If this
        # ever becomes a hard gate it should be a decision, not a side effect of adding a log.
        with caplog.at_level(logging.WARNING, logger="prospector.bridge"):
            bridge.publish_pass(_dossier(None))
        assert bridge.catalog_calls[-1]["is_listed"] is True

    def test_a_tagged_pack_says_nothing(self, bridge, caplog):
        with caplog.at_level(logging.WARNING, logger="prospector.bridge"):
            bridge.publish_pass(_dossier({
                "sector": "other", "payer": "b2b", "effort": "automatable",
                "mechanism": "vertical_tool", "advantages": ["ops"],
            }))
        assert not [m for m in _warnings(caplog) if "NO sector" in m]
        call = bridge.catalog_calls[-1]
        assert call["metadata"]["sector"] == "other"
        assert call["metadata"]["payer"] == "b2b"

    def test_an_invented_sector_warns_rather_than_shipping(self, bridge, caplog):
        """`normalize` drops a value outside the vocabulary — the pack must then read as
        untagged, not as quietly tagged with something the storefront cannot render."""
        with caplog.at_level(logging.WARNING, logger="prospector.bridge"):
            bridge.publish_pass(_dossier({"sector": "aquaculture"}))
        assert [m for m in _warnings(caplog) if "NO sector" in m]
        assert "sector" not in bridge.catalog_calls[-1]["metadata"]


class TestDerivedFacetsFillHolesAtPublish:
    """The publish path consults the dossier's own fields for the two facets that restate one.

    Until 2026-08-01 it did not, and that made the mechanical half of the facet backfill a
    one-off patch: `effort` was filled on 14 live packs by reading `automatability` and
    `structural_form`, two fields nothing in `publish_pass` had ever opened, so the identical
    hole would reopen on the next pack whose generation dropped the facets block.
    """

    def test_effort_and_mechanism_are_derived_when_generation_omits_them(self, bridge):
        bridge.publish_pass(_dossier(
            {"sector": "other", "payer": "b2b"},
            automatability=0.9,
            structural_form="vertical_tool",
        ))
        meta = bridge.catalog_calls[-1]["metadata"]
        assert meta["effort"] == "automatable"
        assert meta["mechanism"] == "vertical_tool"

    def test_generation_is_never_overwritten(self, bridge):
        """0.9 on its own derives `automatable`; generation said `hands_on` and it must win.

        This is the authority order tools/backfill_facets.py uses, asserted at the other end of
        the pipe: derivation fills holes, it never corrects a human or a model that spoke.
        """
        bridge.publish_pass(_dossier(
            {"sector": "other", "effort": "hands_on"},
            automatability=0.9,
            structural_form="vertical_tool",
        ))
        assert bridge.catalog_calls[-1]["metadata"]["effort"] == "hands_on"

    def test_the_judgement_facets_are_never_derived(self, bridge):
        """A candidate rich enough to derive both derivable facets must STILL publish untagged
        on the four that need a judgement about who pays or what the buyer already has."""
        bridge.publish_pass(_dossier(None, automatability=0.9, structural_form="vertical_tool"))
        meta = bridge.catalog_calls[-1]["metadata"]
        assert meta["effort"] == "automatable"
        for judgement in ("sector", "payer", "commitment", "advantages"):
            assert judgement not in meta, f"{judgement} was derived; it is a judgement call"

    def test_off_vocabulary_structural_form_is_refused_not_coerced(self, bridge):
        """`vertical_saas` is one underscore from `vertical_tool` and is live in real dossiers.
        Nearness is not membership, so the pack publishes with no mechanism at all."""
        bridge.publish_pass(_dossier({"sector": "other"}, structural_form="vertical_saas"))
        assert "mechanism" not in bridge.catalog_calls[-1]["metadata"]
